### ISSUE TITLE
feat: add result page

### ISSUE THREAD

**Issue by yuuki-hi** [tf63/kawakera_advance#21]
**内容**
- APIのレスポンスを表示するページ
- 画像入力後に遷移

**Comment by tf63** [comment]
**サンプル**
<img width="701" alt="image" src="https://github.com/tf63/kawakera_advance/assets/74246282/c0f54995-466a-4f7f-b9e9-577580ebd0bb">

**Comment by yuuki-hi** [comment]
![Screenshot from 2023-06-18 14-17-14](https://github.com/tf63/kawakera_advance/assets/108603238/a33f4df3-9c03-4d50-bc23-502a64180619)
