### ISSUE TITLE
feat: ChatGPT APIの利用

### ISSUE THREAD

**Issue by tf63** [tf63/kawakera_advance#27]
**ChatGPT API**
- 日本語でやって良い?
- 英語で調べて日本語で答えてくださいと質問する?

**Comment by ultimatemagic79** [comment]
> 英語で調べて日本語で答えてくださいと質問する?

質問は英語で用意して，回答を日本語でお願いします．の方が良いかも．deepLに通す必要がなくなる


**GPTから受け取る内容**
- food=string
- area=string
- trivia=string
- type=string
- base_stats=int[H,A,B,C,D,S]
