### ISSUE TITLE
docs: プレゼン発表の準備

### ISSUE THREAD

**Issue by rabbit-313** [tf63/kawakera_advance#53]
### ブラッシュアップ
  - どんな追加開発を行った？
  - 改善点は何？
### 完成度
  - 機能の実装度
  - UI (みため）
  - UX (ユーザ体験）
### 技術的な挑戦
  - どんな新しい技術に挑戦した？
  - どんな成長を得られた？

**Comment by rabbit-313** [comment]
## 回答
### どんな追加開発を行った？ (差分点を強調)
**バックエンド**
- ViewからAPIに
- 画像そのままからセグメンテーション画像に
- 動物のステータスをAIが評価してくれるように

**フロントエンド**
- テンプレートを返すのからReactに変更
- SPA化
- デザインをBootStrapから自作のデザインに変更

### 改善点は何？
**課題_1**
- ChatGPTなどのAPI通信時間が長い

**解決策_1**
- DBに保存されたものを使いまわすことで通信時間を減らす
- 通信待機中に退屈させないような工夫を行った
- DeepLを使わずにChatGPTだけで完結させた

**課題_2**
- UIが悪かった

**解決策_1**
- React関係

### どんな新しい技術に挑戦した？
**バックエンド**
- セグメンテーション
- DjangoのRestAPI開発

**フロントエンド**
- React


### チーム開発
- CI
- チケット管理

### どんな成長を得られた？
**技術**
- React
- API開発
- 本番環境を意識した開発

**チーム開発**
- CI (テストを意識した開発)
- Issueでタスク管理
- 作業報告を適宜行う (フロントとバックエンドでのちに勉強会を行うため)
- オフラインでミーティングをこまめに

**Comment by tf63** [comment]
### 技術スタック
**インフラ**
- Docker
- Docker compose (タコ)
- AWS EC2
- AWS RDS

**フロント**
- React
- TypeScript
- Vite (ヴィート)

**バックエンド**
- Django
- Django REST Framework
- Python
- PostgreSQL
- pg4admin

**API**
- Huggingface
- ChatGPT

**開発ツール**
- Github
- Github Issue (チケット管理ツール，ロゴあるかわかんない)
- Github Actions (CIツール)
- Figma (デザインツール)
- Miro (設計)
- VSCode (開発)

**Comment by tf63** [comment]
### チーム開発する上で気をつけたこと (どんな成長を得られた? に繋がる話)
- PRのレビューを怠らないために，レビュー時に作業内容の要約をしてもらう
- フロントとバックエンドのデータのやり取り
